variable "cluster_name" {}
variable "environment" {}
variable "region" {}
variable "vpc_id" {}
variable "service_name" {}
variable "log_group" {}
variable "log_retention" {}
variable "task_family" {}
variable "template_file" {}
variable "desired_count" {}
variable "iam_task_role" {}
variable "ecr_repository_url" {}
variable "ecr_repository_tag" {}
variable "cluster_id" {}
variable "max_service_capacity" {}
variable "min_service_capacity" {}
variable "ecs_cluster_name" {}
variable "svc_cpu_high" {}
variable "svc_alarm_cpu_high_operator" {}
variable "svc_alarm_cpu_high_periods" {}
variable "svc_alarm_cpu_high_period_length" {}
variable "svc_alarm_cpu_high_threshold" {}
variable "svc_cpu_low" {}
variable "svc_alarm_cpu_low_operator" {}
variable "svc_alarm_cpu_low_periods" {}
variable "svc_alarm_cpu_low_period_length" {}
variable "svc_alarm_cpu_low_threshold" {}
